In [18]:
%matplotlib inline
import torch
import numpy as np
import random

import torch.utils.data as Data
from torch import nn
from torch.nn import init
import torch.optim as optim

In [19]:
num_inputs = 2
num_examples = 1000

true_w = [2, -3.4]
true_b = 4.2


# 数据生成
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)),
                        dtype=torch.float
                       )


labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), 
                       dtype=torch.float
                      )

batch_size = 10

In [20]:
# 读取数据
dataSet = Data.TensorDataset(features, labels)

# 随机读取小批量
data_iter = Data.DataLoader(dataSet, batch_size, shuffle=True)


class LinearNet(nn.Module):
    
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)

    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y


net = LinearNet(num_inputs)

net = nn.Sequential(
    nn.Linear(num_inputs, 1)
)


# 初始化模型参数
init.normal_(net[0].weight, mean=0, std=0.01)

# 也可以直接修改bias的data: net[0].bias.data.fill_(0)
init.constant_(net[0].bias, val=0)  

loss = nn.MSELoss()

optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.03
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [21]:
# 训练
num_epochs = 3

for epoch in range(1,num_epochs + 1):
    for X,y in data_iter:
        output = net(X)
        l = loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
        pass
    
    print(f'epoch {epoch}, loss {l.item()}')
    

dense = net[0]

print('true_w: ', true_w, dense.weight)
print("")
print('true_b: ', true_b, dense.bias)

epoch 1, loss 0.000314960052492097
epoch 2, loss 0.00012443836021702737
epoch 3, loss 7.05700003891252e-05
true_w:  [2, -3.4] Parameter containing:
tensor([[ 1.9998, -3.4000]], requires_grad=True)

true_b:  4.2 Parameter containing:
tensor([4.2006], requires_grad=True)


In [27]:
%matplotlib inline
import torch
import numpy as np
import random
import torch.utils.data as Data
from torch import nn
from torch.nn import init
import torch.optim as optim


num_inputs = 2
num_examples = 1000

true_w = [2, -3.4]
true_b = 4.2

# 数据生成
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)),
                        dtype=torch.float
                       )

labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), 
                       dtype=torch.float
                      )

batch_size = 10

# 将训练数据的特征和标签组合
dataSet = Data.TensorDataset(features, labels)

# 随机读取小批量
data_iter = Data.DataLoader(dataSet, batch_size, shuffle=True)


class LinearNet(nn.Module):
    
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)

    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y


net = LinearNet(num_inputs)

net = nn.Sequential(
    nn.Linear(num_inputs, 1)
)


# 初始化模型参数
init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)  


# 定义损失函数
loss = nn.MSELoss()

# 定义优化算法
optimizer = optim.SGD(net.parameters(), lr=0.03)


# 训练
num_epochs = 3

for epoch in range(1,num_epochs + 1):
    for X,y in data_iter:
        output = net(X)
        l = loss(output,y.view(-1,1))
        optimizer.zero_grad()  # 梯度清零,等价于net.zero_grad()
        l.backward()
        optimizer.step()
        pass
    
    print(f'epoch {epoch}, loss {l.item()}')
    

dense = net[0]

print('true_w: ', true_w, dense.weight)
print("")
print('true_b: ', true_b, dense.bias)

epoch 1, loss 0.00031990851857699454
epoch 2, loss 7.793378608766943e-05
epoch 3, loss 8.541814895579591e-05
true_w:  [2, -3.4] Parameter containing:
tensor([[ 2.0002, -3.3998]], requires_grad=True)

true_b:  4.2 Parameter containing:
tensor([4.2004], requires_grad=True)
