In [1]:
import torch

print(torch.__version__)

def get_device():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    return device

if torch.cuda.is_available():
    
    print("GPU是否可用: \t", torch.cuda.is_available())
    
    print("GPU数量: \t",    torch.cuda.device_count())
    
    print("GPU索引号: \t",   torch.cuda.current_device())
    
    print("GPU名称: \t",     torch.cuda.get_device_name())

    print("cuDNN是否可用: \t", torch.backends.cudnn.version())  # 8500
else:
    print("warn: 当前服务器GPU不可用")

2.0.1+cu118
GPU是否可用: 	 True
GPU数量: 	 1
GPU索引号: 	 0
GPU名称: 	 NVIDIA GeForce RTX 4060 Laptop GPU
cuDNN是否可用: 	 8700


## 2.2.1 创建`Tensor`

In [2]:
x = torch.empty(5, 4, 4)

x

tensor([[[2.9387e-39, 2.9388e-39, 9.1840e-40, 2.9388e-39],
         [2.9388e-39, 1.0469e-38, 1.0102e-38, 3.6736e-39],
         [6.5204e-39, 7.8061e-39, 2.8587e+12, 2.1338e+32],
         [2.9388e-39, 1.0653e-38, 4.0408e-39, 1.0653e-38]],

        [[1.0469e-38, 9.5510e-39, 9.0918e-39, 9.1837e-39],
         [4.2246e-39, 1.0561e-38, 8.9082e-39, 8.9082e-39],
         [9.9184e-39, 9.0000e-39, 9.2755e-39, 3.7653e-39],
         [9.1841e-40, 2.9388e-39, 2.9388e-39, 2.9387e-39]],

        [[2.9388e-39, 1.0286e-38, 9.6429e-39, 1.0653e-38],
         [3.1225e-39, 7.3469e-39, 7.0836e+22, 5.3788e-39],
         [8.4489e-39, 3.1226e-39, 2.9388e-39, 2.9388e-39],
         [1.0653e-38, 1.0469e-38, 9.5510e-39, 9.0918e-39]],

        [[9.1837e-39, 4.2246e-39, 9.2755e-39, 9.6429e-39],
         [9.2755e-39, 9.0918e-39, 1.0745e-38, 1.0653e-38],
         [3.7653e-39, 9.1841e-40, 2.9388e-39, 2.9388e-39],
         [2.9387e-39, 2.9388e-39, 1.0286e-38, 9.6429e-39]],

        [[1.0653e-38, 3.1225e-39, 7.3469e-39, 1.

创建一个5x3 的long 型全0的`Tensor`:

In [3]:
x = torch.zeros(3, 4, 3, dtype=torch.long)

x

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [5]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

print('size:  ', x.size())
print('shape: ', x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0722, -0.0376,  0.3482],
        [ 0.2779,  0.7696,  0.3124],
        [ 0.3978,  0.3552,  0.2303],
        [ 1.5174, -1.7307, -0.8435],
        [ 0.1333,  0.0837, -0.3821]])
size:   torch.Size([5, 3])
shape:  torch.Size([5, 3])


In [6]:
y = torch.eye(64)
print(y)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])


In [7]:
y = torch.randn(64)
y

tensor([-1.4418e+00,  3.5800e-01,  1.1721e+00, -1.1008e+00,  9.3169e-01,
         7.6637e-01, -8.6546e-02, -7.8399e-01, -1.1144e+00, -1.7153e-01,
         4.4690e-02, -9.2580e-01,  1.5841e-01,  4.4348e-01,  5.2745e-01,
        -1.6923e+00,  1.6283e+00,  2.5323e-01, -8.3921e-01, -1.3499e+00,
         5.4365e-01,  1.0307e+00, -1.1154e+00, -8.8771e-01, -4.1641e-01,
         2.6717e-01,  1.3613e-02,  1.3925e+00,  1.5686e+00, -1.2617e+00,
         1.4933e-01,  6.1900e-02,  6.9021e-01, -5.1229e-01, -8.1467e-01,
        -2.8275e+00,  1.1184e+00,  3.7434e-01, -5.0925e-01, -2.3269e-02,
         1.6380e+00, -1.2588e-01,  1.1079e+00,  4.8453e-01,  6.1135e-01,
        -2.1648e-03,  3.5612e-01, -8.7305e-01, -1.0378e+00,  1.1635e+00,
        -5.2476e-01,  2.3020e-01,  2.1434e-01,  3.3487e-01, -4.3829e-01,
         4.6382e-01,  1.0404e+00, -1.4902e+00, -2.0388e+00, -1.6802e+00,
        -5.9098e-02, -2.1597e-01, -4.9333e-01, -1.4375e+00])

In [8]:
y = torch.rand(64)
y

tensor([0.9486, 0.0117, 0.9010, 0.9850, 0.2764, 0.3299, 0.5158, 0.4235, 0.8476,
        0.9334, 0.1126, 0.3768, 0.7841, 0.7867, 0.1440, 0.8243, 0.6731, 0.6128,
        0.3812, 0.0656, 0.7432, 0.2785, 0.1113, 0.2467, 0.0551, 0.6618, 0.7719,
        0.0158, 0.3398, 0.4767, 0.4028, 0.1692, 0.4641, 0.8919, 0.7167, 0.5713,
        0.5820, 0.0381, 0.5630, 0.2116, 0.4347, 0.3830, 0.5683, 0.9564, 0.2556,
        0.2405, 0.1098, 0.6793, 0.9762, 0.7028, 0.4481, 0.0126, 0.7802, 0.4378,
        0.4890, 0.5259, 0.6746, 0.3653, 0.6023, 0.0690, 0.7237, 0.5265, 0.8125,
        0.4195])

In [9]:
y = torch.randperm(10)
print(y)

tensor([3, 9, 1, 8, 7, 6, 0, 5, 4, 2])


## 2.2.2 操作

本小节介绍`Tensor`的各种操作。

### 算术操作

在PyTorch中，同一种操作可能有很多种形式，下面用加法作为例子。

* **加法形式一**

In [10]:
y = torch.rand(5, 4)
x = torch.rand(5, 4)


# print(x + y)
print(torch.add(x, y))

tensor([[0.9877, 0.5525, 0.7596, 0.9965],
        [0.6894, 1.7523, 1.5193, 0.9238],
        [1.1373, 1.0975, 0.7698, 0.7071],
        [1.5638, 0.8873, 0.9559, 0.9408],
        [1.7249, 0.3225, 0.9300, 0.8597]])


**加法形式二**

In [11]:
res = torch.empty(5, 4)

torch.add(x, y, out=res)
print(res)

tensor([[0.9877, 0.5525, 0.7596, 0.9965],
        [0.6894, 1.7523, 1.5193, 0.9238],
        [1.1373, 1.0975, 0.7698, 0.7071],
        [1.5638, 0.8873, 0.9559, 0.9408],
        [1.7249, 0.3225, 0.9300, 0.8597]])


**加法形式三、inplace**

In [12]:
y.add_(x)
print(y)

tensor([[0.9877, 0.5525, 0.7596, 0.9965],
        [0.6894, 1.7523, 1.5193, 0.9238],
        [1.1373, 1.0975, 0.7698, 0.7071],
        [1.5638, 0.8873, 0.9559, 0.9408],
        [1.7249, 0.3225, 0.9300, 0.8597]])


### 索引

我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [13]:
x

tensor([[0.5947, 0.5238, 0.4946, 0.2793],
        [0.0976, 0.9018, 0.8776, 0.4283],
        [0.9780, 0.4874, 0.2762, 0.4631],
        [0.8511, 0.0607, 0.4643, 0.8542],
        [0.9201, 0.1615, 0.1940, 0.0256]])

In [14]:
y = x[0, :]

y += 1
print(y)

print(x[0, :])

tensor([1.5947, 1.5238, 1.4946, 1.2793])
tensor([1.5947, 1.5238, 1.4946, 1.2793])


### 改变形状

用`view()`来改变`Tensor`的形状：

In [15]:
x

tensor([[1.5947, 1.5238, 1.4946, 1.2793],
        [0.0976, 0.9018, 0.8776, 0.4283],
        [0.9780, 0.4874, 0.2762, 0.4631],
        [0.8511, 0.0607, 0.4643, 0.8542],
        [0.9201, 0.1615, 0.1940, 0.0256]])

In [16]:
y = x.view(20)

print(y)
print(y.size())

tensor([1.5947, 1.5238, 1.4946, 1.2793, 0.0976, 0.9018, 0.8776, 0.4283, 0.9780,
        0.4874, 0.2762, 0.4631, 0.8511, 0.0607, 0.4643, 0.8542, 0.9201, 0.1615,
        0.1940, 0.0256])
torch.Size([20])


In [17]:
z = x.view(-1, 5)

print(z)
print(z.size())
print(z.shape)

tensor([[1.5947, 1.5238, 1.4946, 1.2793, 0.0976],
        [0.9018, 0.8776, 0.4283, 0.9780, 0.4874],
        [0.2762, 0.4631, 0.8511, 0.0607, 0.4643],
        [0.8542, 0.9201, 0.1615, 0.1940, 0.0256]])
torch.Size([4, 5])
torch.Size([4, 5])


注意`view()`返回的新`Tensor`与源`Tensor`虽然可能有不同的`size`，但是是共享`data`的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [18]:
x += 1
print(x)
print(y)

tensor([[2.5947, 2.5238, 2.4946, 2.2793],
        [1.0976, 1.9018, 1.8776, 1.4283],
        [1.9780, 1.4874, 1.2762, 1.4631],
        [1.8511, 1.0607, 1.4643, 1.8542],
        [1.9201, 1.1615, 1.1940, 1.0256]])
tensor([2.5947, 2.5238, 2.4946, 2.2793, 1.0976, 1.9018, 1.8776, 1.4283, 1.9780,
        1.4874, 1.2762, 1.4631, 1.8511, 1.0607, 1.4643, 1.8542, 1.9201, 1.1615,
        1.1940, 1.0256])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个`reshape()`可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用`clone`创造一个副本然后再使用`view`。[参考此处](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

In [19]:
x_cp = x.clone().view(20)

x -= 1

print(x)
print(x_cp)

tensor([[1.5947, 1.5238, 1.4946, 1.2793],
        [0.0976, 0.9018, 0.8776, 0.4283],
        [0.9780, 0.4874, 0.2762, 0.4631],
        [0.8511, 0.0607, 0.4643, 0.8542],
        [0.9201, 0.1615, 0.1940, 0.0256]])
tensor([2.5947, 2.5238, 2.4946, 2.2793, 1.0976, 1.9018, 1.8776, 1.4283, 1.9780,
        1.4874, 1.2762, 1.4631, 1.8511, 1.0607, 1.4643, 1.8542, 1.9201, 1.1615,
        1.1940, 1.0256])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [20]:
x = torch.randn(1)

x

tensor([0.4736])

In [21]:
# py数字类型
x.item()

0.47360336780548096

### 线性代数

另外，PyTorch还支持一些线性函数，这里提一下，免得用起来的时候自己造轮子，具体用法参考官方文档。如下表所示：
PyTorch中的`Tensor`支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考[官方文档](https://pytorch.org/docs/stable/tensors.html)。

## 2.2.3 广播机制

前面我们看到如何对两个形状相同的`Tensor`做按元素运算。当对两个形状不同的`Tensor`按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。例如：

In [22]:
x = torch.arange(1, 3).view(1, 2)

x

tensor([[1, 2]])

In [23]:
y = torch.arange(1, 4).view(3, 1)

y

tensor([[1],
        [2],
        [3]])

In [24]:
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

## 2.2.4 运算的内存开销

前面说了，索引操作是不会开辟新内存的，而像`y = x + y`这样的运算是会新开内存的，然后将`y`指向新内存。为了演示这一点，我们可以使用Python自带的`id`函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [25]:
x = torch.tensor([1, 22, 3])

y = torch.tensor([41, 32, 3])

In [26]:
id_before = id(y)
id_before

140647201662000

In [27]:
y = y + x

print(id(y))

140647207597728


如果想指定结果到原来的`y`的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把`x + y`的结果通过`[:]`写进`y`对应的内存中。

In [28]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])
print(id(y))

y[:] = y + x
print(id(y))

140647201665600
140647201665600


我们还可以使用运算符全名函数中的`out`参数或者自加运算符`+=`(也即`add_()`)达到上述效果，例如`torch.add(x, y, out=y)`和`y += x`(`y.add_(x)`)。

In [29]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])


print(id(y))
torch.add(x, y, out=y)

print(id(y))

140647201666720
140647201666720


## 2.2.5 `Tensor`和NumPy相互转换

我们很容易用`numpy()`和`from_numpy()`将`Tensor`和NumPy中的数组相互转换。但是需要注意的一点是：
**这两个函数所产生的的`Tensor`和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**
> 还有一个常用的将NumPy中的array转换成`Tensor`的方法就是`torch.tensor()`, 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的`Tensor`和原来的数据不再共享内存。

### `Tensor`转NumPy

使用`numpy()`将`Tensor`转换成NumPy数组:

In [30]:
a = torch.ones(5)  # tensor([1., 1., 1., 1., 1.])

b = a.numpy()      # array([1., 1., 1., 1., 1.], dtype=float32)

In [31]:
a += 1  # tensor([2., 2., 2., 2., 2.])

In [32]:
b += 1  # array([4., 4., 4., 4., 4.], dtype=float32)

In [33]:
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

使用`from_numpy()`将NumPy数组转换成`Tensor`:

In [34]:
import numpy as np

In [35]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
a += 1
b += 1
print(a, b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


所有在CPU上的`Tensor`（除了`CharTensor`）都支持与NumPy数组相互转换。

此外上面提到还有一个常用的方法就是直接用`torch.tensor()`将NumPy数组转换成`Tensor`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [37]:
c = torch.tensor(a)

a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

用方法`to()`可以将`Tensor`在CPU和GPU（需要硬件支持）之间相互移动。

In [38]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    print("x: ", x)
    z = x + y

    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型