In [1]:
import torch

## 2.2.1 创建`Tensor`

In [2]:
x = torch.empty(5, 4, 4)

x

tensor([[[ 2.1763e+16,  4.5653e-41,  1.5414e-44,  1.5632e-13],
         [ 0.0000e+00,  0.0000e+00,  1.1210e-44,  0.0000e+00],
         [ 0.0000e+00,  2.4074e-35, -1.7439e+38,  1.2552e-28],
         [-1.8630e+38,  1.2506e+01,  6.3923e+05,  2.0404e+03]],

        [[ 4.3368e-19,  6.9333e-27,  2.4751e-03,  4.1359e-25],
         [-2.3679e+38,  1.5362e-33,  9.5219e-24,  5.7088e-31],
         [-2.5531e+38,  1.9185e-07,  1.1190e-22,  1.0323e+04],
         [ 1.2583e+07,  1.2500e-01, -1.8517e+38,  9.6983e-21]],

        [[        nan, -2.2198e+38, -1.2899e-13,  5.5669e-15],
         [ 3.1617e-18,  4.5654e-41,  3.3118e+16,  4.5653e-41],
         [ 7.8568e-02, -2.1600e-21,  3.1615e-18,  4.5654e-41],
         [ 1.3297e-38,  0.0000e+00,  2.0435e+05, -2.4956e+33]],

        [[ 3.1060e-18,  4.5654e-41,  3.1814e+16,  4.5653e-41],
         [-4.9109e-09,  6.0299e+27,  3.1060e-18,  4.5654e-41],
         [ 3.1829e+16,  4.5653e-41,  3.8353e-13, -9.6498e-07],
         [ 3.1060e-18,  4.5654e-41,  3.1828e+16, 

创建一个5x3 的long 型全0的`Tensor`:

In [3]:
x = torch.zeros(3, 4, 3, dtype=torch.long)

x

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [5]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

print('size:  ', x.size())
print('shape: ', x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2195,  1.0439,  1.1368],
        [-1.3194, -0.5096,  0.8286],
        [ 0.8448,  0.2398,  0.1438],
        [ 0.3337, -0.4614,  1.4635],
        [-0.6835, -0.6558,  1.0082]])
size:   torch.Size([5, 3])
shape:  torch.Size([5, 3])


In [6]:
y = torch.eye(64)
print(y)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])


In [7]:
y = torch.randn(64)
y

tensor([ 1.3029, -0.5865, -0.8799,  0.3197, -0.7423,  1.4456, -1.2752, -0.5238,
         1.1298,  0.3197, -1.1010, -1.2478,  1.0448, -0.0836, -0.0628, -0.7634,
        -0.9206,  1.2261,  0.2418, -1.0231,  1.0527, -0.0241,  0.0277,  0.5455,
         2.1207,  0.1482, -0.2799,  0.1529, -0.2272,  0.5993,  0.1463,  0.0338,
         0.5076, -0.3554,  0.3524, -1.5380, -1.1797,  0.3278,  0.9795,  0.0477,
        -0.7506,  0.3196, -0.0763, -1.3968, -0.7160, -0.3546,  0.5868,  0.0768,
        -0.9024, -0.8028,  1.4882, -0.6238,  0.3952, -1.0506,  0.0314, -0.7594,
         1.0910,  1.1875, -1.1570, -2.2548, -0.0257,  1.8088,  1.0442, -1.0703])

In [8]:
y = torch.rand(64)
y

tensor([0.4211, 0.1936, 0.2383, 0.0649, 0.3216, 0.4872, 0.6417, 0.8217, 0.0875,
        0.3177, 0.5359, 0.0290, 0.2645, 0.2497, 0.0412, 0.7011, 0.8434, 0.4821,
        0.1230, 0.6493, 0.2068, 0.3269, 0.2174, 0.5611, 0.7064, 0.8559, 0.9040,
        0.0532, 0.5907, 0.5689, 0.5363, 0.5164, 0.1346, 0.4984, 0.9766, 0.6854,
        0.7966, 0.8841, 0.1855, 0.7948, 0.8801, 0.7732, 0.4593, 0.0750, 0.0924,
        0.1855, 0.3713, 0.2837, 0.8220, 0.8142, 0.5547, 0.1904, 0.3534, 0.2551,
        0.7602, 0.5715, 0.5139, 0.0332, 0.5712, 0.5342, 0.9037, 0.8330, 0.3634,
        0.5348])

In [9]:
y = torch.randperm(10)
print(y)

tensor([0, 6, 3, 1, 8, 9, 4, 2, 5, 7])


## 2.2.2 操作

本小节介绍`Tensor`的各种操作。

### 算术操作

在PyTorch中，同一种操作可能有很多种形式，下面用加法作为例子。

* **加法形式一**

In [10]:
y = torch.rand(5, 4)
x = torch.rand(5, 4)


# print(x + y)
print(torch.add(x, y))

tensor([[0.2146, 1.1717, 0.8728, 1.8637],
        [0.9214, 0.7672, 1.0782, 1.0130],
        [1.0224, 1.1420, 0.2737, 1.4637],
        [0.0490, 0.8066, 1.4164, 0.8094],
        [0.8711, 1.6137, 0.7634, 0.9249]])


**加法形式二**

In [11]:
res = torch.empty(5, 4)

torch.add(x, y, out=res)
print(res)

tensor([[0.2146, 1.1717, 0.8728, 1.8637],
        [0.9214, 0.7672, 1.0782, 1.0130],
        [1.0224, 1.1420, 0.2737, 1.4637],
        [0.0490, 0.8066, 1.4164, 0.8094],
        [0.8711, 1.6137, 0.7634, 0.9249]])


**加法形式三、inplace**

In [12]:
y.add_(x)
print(y)

tensor([[0.2146, 1.1717, 0.8728, 1.8637],
        [0.9214, 0.7672, 1.0782, 1.0130],
        [1.0224, 1.1420, 0.2737, 1.4637],
        [0.0490, 0.8066, 1.4164, 0.8094],
        [0.8711, 1.6137, 0.7634, 0.9249]])


### 索引

我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [13]:
x

tensor([[0.1588, 0.1749, 0.3355, 0.8658],
        [0.4232, 0.1905, 0.2179, 0.4141],
        [0.7828, 0.9267, 0.1791, 0.5791],
        [0.0125, 0.5375, 0.6253, 0.1747],
        [0.0489, 0.8014, 0.1127, 0.7466]])

In [14]:
y = x[0, :]

y += 1
print(y)

print(x[0, :])

tensor([1.1588, 1.1749, 1.3355, 1.8658])
tensor([1.1588, 1.1749, 1.3355, 1.8658])


### 改变形状

用`view()`来改变`Tensor`的形状：

In [15]:
x

tensor([[1.1588, 1.1749, 1.3355, 1.8658],
        [0.4232, 0.1905, 0.2179, 0.4141],
        [0.7828, 0.9267, 0.1791, 0.5791],
        [0.0125, 0.5375, 0.6253, 0.1747],
        [0.0489, 0.8014, 0.1127, 0.7466]])

In [20]:
y = x.view(20)

print(y)
print(y.size())

tensor([1.1588, 1.1749, 1.3355, 1.8658, 0.4232, 0.1905, 0.2179, 0.4141, 0.7828,
        0.9267, 0.1791, 0.5791, 0.0125, 0.5375, 0.6253, 0.1747, 0.0489, 0.8014,
        0.1127, 0.7466])
torch.Size([20])


In [21]:
z = x.view(-1, 5)

print(z)
print(z.size())
print(z.shape)

tensor([[1.1588, 1.1749, 1.3355, 1.8658, 0.4232],
        [0.1905, 0.2179, 0.4141, 0.7828, 0.9267],
        [0.1791, 0.5791, 0.0125, 0.5375, 0.6253],
        [0.1747, 0.0489, 0.8014, 0.1127, 0.7466]])
torch.Size([4, 5])
torch.Size([4, 5])


注意`view()`返回的新`Tensor`与源`Tensor`虽然可能有不同的`size`，但是是共享`data`的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [22]:
x += 1
print(x)
print(y)

tensor([[2.1588, 2.1749, 2.3355, 2.8658],
        [1.4232, 1.1905, 1.2179, 1.4141],
        [1.7828, 1.9267, 1.1791, 1.5791],
        [1.0125, 1.5375, 1.6253, 1.1747],
        [1.0489, 1.8014, 1.1127, 1.7466]])
tensor([2.1588, 2.1749, 2.3355, 2.8658, 1.4232, 1.1905, 1.2179, 1.4141, 1.7828,
        1.9267, 1.1791, 1.5791, 1.0125, 1.5375, 1.6253, 1.1747, 1.0489, 1.8014,
        1.1127, 1.7466])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个`reshape()`可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用`clone`创造一个副本然后再使用`view`。[参考此处](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

In [23]:
x_cp = x.clone().view(20)

x -= 1

print(x)
print(x_cp)

tensor([[1.1588, 1.1749, 1.3355, 1.8658],
        [0.4232, 0.1905, 0.2179, 0.4141],
        [0.7828, 0.9267, 0.1791, 0.5791],
        [0.0125, 0.5375, 0.6253, 0.1747],
        [0.0489, 0.8014, 0.1127, 0.7466]])
tensor([2.1588, 2.1749, 2.3355, 2.8658, 1.4232, 1.1905, 1.2179, 1.4141, 1.7828,
        1.9267, 1.1791, 1.5791, 1.0125, 1.5375, 1.6253, 1.1747, 1.0489, 1.8014,
        1.1127, 1.7466])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [24]:
x = torch.randn(1)

x

tensor([0.2247])

In [25]:
# py数字类型
x.item()

0.22468601167201996

### 线性代数

另外，PyTorch还支持一些线性函数，这里提一下，免得用起来的时候自己造轮子，具体用法参考官方文档。如下表所示：
PyTorch中的`Tensor`支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考[官方文档](https://pytorch.org/docs/stable/tensors.html)。

## 2.2.3 广播机制

前面我们看到如何对两个形状相同的`Tensor`做按元素运算。当对两个形状不同的`Tensor`按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。例如：

In [26]:
x = torch.arange(1, 3).view(1, 2)

x

tensor([[1, 2]])

In [27]:
y = torch.arange(1, 4).view(3, 1)

y

tensor([[1],
        [2],
        [3]])

In [28]:
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

## 2.2.4 运算的内存开销

前面说了，索引操作是不会开辟新内存的，而像`y = x + y`这样的运算是会新开内存的，然后将`y`指向新内存。为了演示这一点，我们可以使用Python自带的`id`函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [29]:
x = torch.tensor([1, 22, 3])

y = torch.tensor([41, 32, 3])

In [30]:
id_before = id(y)
id_before

139927259647888

In [31]:
y = y + x

print(id(y))

139927264763472


如果想指定结果到原来的`y`的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把`x + y`的结果通过`[:]`写进`y`对应的内存中。

In [32]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])
print(id(y))

y[:] = y + x
print(id(y))

139927255739824
139927255739824


我们还可以使用运算符全名函数中的`out`参数或者自加运算符`+=`(也即`add_()`)达到上述效果，例如`torch.add(x, y, out=y)`和`y += x`(`y.add_(x)`)。

In [33]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])


print(id(y))
torch.add(x, y, out=y)

print(id(y))

139927255737344
139927255737344


## 2.2.5 `Tensor`和NumPy相互转换

我们很容易用`numpy()`和`from_numpy()`将`Tensor`和NumPy中的数组相互转换。但是需要注意的一点是：
**这两个函数所产生的的`Tensor`和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**
> 还有一个常用的将NumPy中的array转换成`Tensor`的方法就是`torch.tensor()`, 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的`Tensor`和原来的数据不再共享内存。

### `Tensor`转NumPy

使用`numpy()`将`Tensor`转换成NumPy数组:

In [34]:
a = torch.ones(5)  # tensor([1., 1., 1., 1., 1.])

b = a.numpy()      # array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
a += 1  # tensor([2., 2., 2., 2., 2.])

In [36]:
b += 1  # array([4., 4., 4., 4., 4.], dtype=float32)

In [37]:
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

使用`from_numpy()`将NumPy数组转换成`Tensor`:

In [38]:
import numpy as np

In [96]:
a = np.ones(5)ß
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [97]:
a += 1
b += 1
print(a, b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


所有在CPU上的`Tensor`（除了`CharTensor`）都支持与NumPy数组相互转换。

此外上面提到还有一个常用的方法就是直接用`torch.tensor()`将NumPy数组转换成`Tensor`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [98]:
c = torch.tensor(a)

a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

用方法`to()`可以将`Tensor`在CPU和GPU（需要硬件支持）之间相互移动。

In [54]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    print("x: ", x)
    z = x + y

    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

x:  tensor([1, 2], device='cuda:0')
tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
