In [8]:
import torch

print(torch.__version__)

def get_device():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    return device

if torch.cuda.is_available():
    
    print("GPU是否可用: \t", torch.cuda.is_available())
    
    print("GPU数量: \t",    torch.cuda.device_count())
    
    print("GPU索引号: \t",   torch.cuda.current_device())
    
    print("GPU名称: \t",     torch.cuda.get_device_name())

    print("cuDNN是否可用: \t", torch.backends.cudnn.version())  # 8500
else:
    print("warn: 当前服务器GPU不可用")

2.1.2+cu121
warn: 当前服务器GPU不可用


## 2.2.1 创建`Tensor`

In [9]:
x = torch.empty(5, 4, 4)

x

tensor([[[3.9779e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.9720e-35, 0.0000e+00, 3.1422e-36, 0.0000e+00],
         [3.2090e-08, 4.5667e-41, 1.4013e-45, 0.0000e+00],
         [2.1019e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 2.1019e-44, 0.0000e+00],
         [9.1844e-41, 1.1551e-40, 4.5919e-41, 8.2957e-43],
         [1.2612e-44, 0.0000e+00, 1.1351e-43, 0.0000e+00],
         [6.5662e-09, 4.5668e-41, 3.9702e-35, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 0.0000e+00, 3.3602e+07],
         [1.0694e-38, 0.0000e+00, 2.9287e-43, 0.0000e+00],
         [3.9748e-35, 0.0000e+00, 3.9753e-35, 0.0000e+00],
         [4.0357e-43, 0.0000e+00, 1.7937e-43, 0.0000e+00]],

        [[3.6308e-41, 0.0000e+00, 2.0000e+00, 1.

创建一个5x3 的long 型全0的`Tensor`:

In [10]:
x = torch.zeros(3, 4, 3, dtype=torch.long)

x

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [11]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [12]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

print('size:  ', x.size())
print('shape: ', x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2266,  0.8919,  0.5978],
        [ 1.1366,  0.5930, -0.4332],
        [-0.6791,  0.4833, -0.0476],
        [ 0.6245,  0.6477,  0.7549],
        [ 0.8478,  0.6537,  0.2291]])
size:   torch.Size([5, 3])
shape:  torch.Size([5, 3])


In [13]:
y = torch.eye(64)
print(y)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])


In [14]:
y = torch.randn(64)
y

tensor([ 0.8562,  0.0162, -0.8818,  0.0425, -0.4928,  0.6058, -1.3946,  0.4521,
         1.2376, -1.0571, -0.3820, -0.5360,  0.0730, -0.6764,  0.6593, -0.4054,
        -1.9695,  0.1872,  0.2067, -0.7811,  0.1520, -1.4976, -1.4786, -0.4096,
         0.1827, -0.2589, -0.7655,  0.9538,  0.5115, -1.0648,  0.6747,  0.6280,
        -0.4409, -1.8957,  0.5452,  0.2896,  0.2916,  0.6166, -0.2446, -0.4511,
         1.6186, -0.9096,  0.1425, -0.2296,  0.3412,  0.2513, -0.8409,  0.1456,
        -1.3513, -0.1735,  0.6996, -1.4951, -0.6815,  0.1725,  0.7337, -0.6078,
         0.6884, -0.4595, -0.4053,  0.4979,  0.7592, -0.4807,  0.4059, -0.8374])

In [15]:
y = torch.rand(64)
y

tensor([0.7255, 0.1689, 0.0551, 0.8263, 0.9467, 0.9058, 0.0214, 0.6162, 0.7000,
        0.2806, 0.6833, 0.1239, 0.8669, 0.6506, 0.0114, 0.5225, 0.5369, 0.1804,
        0.7898, 0.9785, 0.3246, 0.0992, 0.5898, 0.1780, 0.8174, 0.6644, 0.4129,
        0.1550, 0.3288, 0.7950, 0.8638, 0.7235, 0.1996, 0.2858, 0.0629, 0.8356,
        0.0398, 0.4148, 0.9825, 0.3072, 0.0245, 0.8865, 0.5422, 0.0596, 0.8623,
        0.1257, 0.4514, 0.9065, 0.2119, 0.9251, 0.6257, 0.3152, 0.0914, 0.0048,
        0.2759, 0.8895, 0.3243, 0.1085, 0.3022, 0.8230, 0.0397, 0.4627, 0.9222,
        0.9405])

In [16]:
y = torch.randperm(10)
print(y)

tensor([2, 1, 7, 9, 4, 6, 3, 0, 8, 5])


## 2.2.2 操作

本小节介绍`Tensor`的各种操作。

### 算术操作

在PyTorch中，同一种操作可能有很多种形式，下面用加法作为例子。

* **加法形式一**

In [17]:
y = torch.rand(5, 4)
x = torch.rand(5, 4)


# print(x + y)
print(torch.add(x, y))

tensor([[1.2301, 1.0405, 1.2903, 0.2044],
        [0.4817, 1.6636, 0.9836, 1.0394],
        [0.8071, 1.1262, 1.4959, 1.0888],
        [1.3676, 0.1713, 0.6963, 1.1481],
        [0.8899, 1.0434, 1.6534, 1.3122]])


**加法形式二**

In [18]:
res = torch.empty(5, 4)

torch.add(x, y, out=res)
print(res)

tensor([[1.2301, 1.0405, 1.2903, 0.2044],
        [0.4817, 1.6636, 0.9836, 1.0394],
        [0.8071, 1.1262, 1.4959, 1.0888],
        [1.3676, 0.1713, 0.6963, 1.1481],
        [0.8899, 1.0434, 1.6534, 1.3122]])


**加法形式三、inplace**

In [19]:
y.add_(x)
print(y)

tensor([[1.2301, 1.0405, 1.2903, 0.2044],
        [0.4817, 1.6636, 0.9836, 1.0394],
        [0.8071, 1.1262, 1.4959, 1.0888],
        [1.3676, 0.1713, 0.6963, 1.1481],
        [0.8899, 1.0434, 1.6534, 1.3122]])


### 索引

我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [20]:
x

tensor([[0.8203, 0.7846, 0.3871, 0.1898],
        [0.2545, 0.7899, 0.3912, 0.1655],
        [0.0963, 0.7647, 0.7239, 0.2525],
        [0.7002, 0.0357, 0.5449, 0.4116],
        [0.8786, 0.1387, 0.7672, 0.4863]])

In [21]:
y = x[0, :]

y += 1
print(y)

print(x[0, :])

tensor([1.8203, 1.7846, 1.3871, 1.1898])
tensor([1.8203, 1.7846, 1.3871, 1.1898])


### 改变形状

用`view()`来改变`Tensor`的形状：

In [22]:
x

tensor([[1.8203, 1.7846, 1.3871, 1.1898],
        [0.2545, 0.7899, 0.3912, 0.1655],
        [0.0963, 0.7647, 0.7239, 0.2525],
        [0.7002, 0.0357, 0.5449, 0.4116],
        [0.8786, 0.1387, 0.7672, 0.4863]])

In [23]:
y = x.view(20)

print(y)
print(y.size())

tensor([1.8203, 1.7846, 1.3871, 1.1898, 0.2545, 0.7899, 0.3912, 0.1655, 0.0963,
        0.7647, 0.7239, 0.2525, 0.7002, 0.0357, 0.5449, 0.4116, 0.8786, 0.1387,
        0.7672, 0.4863])
torch.Size([20])


In [24]:
z = x.view(-1, 5)

print(z)
print(z.size())
print(z.shape)

tensor([[1.8203, 1.7846, 1.3871, 1.1898, 0.2545],
        [0.7899, 0.3912, 0.1655, 0.0963, 0.7647],
        [0.7239, 0.2525, 0.7002, 0.0357, 0.5449],
        [0.4116, 0.8786, 0.1387, 0.7672, 0.4863]])
torch.Size([4, 5])
torch.Size([4, 5])


注意`view()`返回的新`Tensor`与源`Tensor`虽然可能有不同的`size`，但是是共享`data`的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [25]:
x += 1
print(x)
print(y)

tensor([[2.8203, 2.7846, 2.3871, 2.1898],
        [1.2545, 1.7899, 1.3912, 1.1655],
        [1.0963, 1.7647, 1.7239, 1.2525],
        [1.7002, 1.0357, 1.5449, 1.4116],
        [1.8786, 1.1387, 1.7672, 1.4863]])
tensor([2.8203, 2.7846, 2.3871, 2.1898, 1.2545, 1.7899, 1.3912, 1.1655, 1.0963,
        1.7647, 1.7239, 1.2525, 1.7002, 1.0357, 1.5449, 1.4116, 1.8786, 1.1387,
        1.7672, 1.4863])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个`reshape()`可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用`clone`创造一个副本然后再使用`view`。[参考此处](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

In [26]:
x_cp = x.clone().view(20)

x -= 1

print(x)
print(x_cp)

tensor([[1.8203, 1.7846, 1.3871, 1.1898],
        [0.2545, 0.7899, 0.3912, 0.1655],
        [0.0963, 0.7647, 0.7239, 0.2525],
        [0.7002, 0.0357, 0.5449, 0.4116],
        [0.8786, 0.1387, 0.7672, 0.4863]])
tensor([2.8203, 2.7846, 2.3871, 2.1898, 1.2545, 1.7899, 1.3912, 1.1655, 1.0963,
        1.7647, 1.7239, 1.2525, 1.7002, 1.0357, 1.5449, 1.4116, 1.8786, 1.1387,
        1.7672, 1.4863])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [27]:
x = torch.randn(1)

x

tensor([1.9211])

In [28]:
# py数字类型
x.item()

1.9211440086364746

### 线性代数

另外，PyTorch还支持一些线性函数，这里提一下，免得用起来的时候自己造轮子，具体用法参考官方文档。如下表所示：
PyTorch中的`Tensor`支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考[官方文档](https://pytorch.org/docs/stable/tensors.html)。

## 2.2.3 广播机制

前面我们看到如何对两个形状相同的`Tensor`做按元素运算。当对两个形状不同的`Tensor`按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。例如：

In [29]:
x = torch.arange(1, 3).view(1, 2)

x

tensor([[1, 2]])

In [30]:
y = torch.arange(1, 4).view(3, 1)

y

tensor([[1],
        [2],
        [3]])

In [31]:
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

## 2.2.4 运算的内存开销

前面说了，索引操作是不会开辟新内存的，而像`y = x + y`这样的运算是会新开内存的，然后将`y`指向新内存。为了演示这一点，我们可以使用Python自带的`id`函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [32]:
x = torch.tensor([1, 22, 3])

y = torch.tensor([41, 32, 3])

In [33]:
id_before = id(y)
id_before

139969548364560

In [34]:
y = y + x

print(id(y))

139969528624960


如果想指定结果到原来的`y`的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把`x + y`的结果通过`[:]`写进`y`对应的内存中。

In [35]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])
print(id(y))

y[:] = y + x
print(id(y))

139969528972288
139969528972288


我们还可以使用运算符全名函数中的`out`参数或者自加运算符`+=`(也即`add_()`)达到上述效果，例如`torch.add(x, y, out=y)`和`y += x`(`y.add_(x)`)。

In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 3])


print(id(y))
torch.add(x, y, out=y)

print(id(y))

139969528973088
139969528973088


## 2.2.5 `Tensor`和NumPy相互转换

我们很容易用`numpy()`和`from_numpy()`将`Tensor`和NumPy中的数组相互转换。但是需要注意的一点是：
**这两个函数所产生的的`Tensor`和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**
> 还有一个常用的将NumPy中的array转换成`Tensor`的方法就是`torch.tensor()`, 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的`Tensor`和原来的数据不再共享内存。

### `Tensor`转NumPy

使用`numpy()`将`Tensor`转换成NumPy数组:

In [37]:
a = torch.ones(5)  # tensor([1., 1., 1., 1., 1.])

b = a.numpy()      # array([1., 1., 1., 1., 1.], dtype=float32)

In [38]:
a += 1  # tensor([2., 2., 2., 2., 2.])

In [39]:
b += 1  # array([4., 4., 4., 4., 4.], dtype=float32)

In [40]:
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

使用`from_numpy()`将NumPy数组转换成`Tensor`:

In [43]:
import numpy as np

In [45]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [46]:
a += 1
b += 1
print(a, b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


所有在CPU上的`Tensor`（除了`CharTensor`）都支持与NumPy数组相互转换。

此外上面提到还有一个常用的方法就是直接用`torch.tensor()`将NumPy数组转换成`Tensor`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [47]:
c = torch.tensor(a)

a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

用方法`to()`可以将`Tensor`在CPU和GPU（需要硬件支持）之间相互移动。

In [48]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    print("x: ", x)
    z = x + y

    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型